name: Get PR Directory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get changed files
      id: files
      run: |
        $(git diff --diff-filter=A --name-only origin/main)
