name: Get PR Directory

on:
  pull_request:
    types:
      - closed

jobs:
  get_directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR Directory
        id: pr_directory
        run: |
          # 获取 PR 的文件目录路径
          PR_DIRECTORY=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | xargs -I {} dirname {})
          echo "::set-output name=directory::${PR_DIRECTORY}"

      - name: List files in directory
        run: |
          # 使用获取到的目录路径进行操作
          cd ${{ steps.pr_directory.outputs.directory }}
          ls -l
