name: Get changed files
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get changed files
      id: files
      run: |
        echo "::set-output name=added::$(git diff --diff-filter=A --name-only origin/main)"
    - name: Show added files
      run: echo "Added files: ${{ steps.files.outputs.added }}"
