name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  disable-autolocking:
    runs-on: ubuntu-latest

    steps:
      - name: Disable autolocking for all pull requests
        run: |
          curl -X PUT -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/branches/main/protection \
            -d '{
              "enforce_admins": true,
              "required_status_checks": null,
              "restrictions": null,
              "required_pull_request_reviews": null,
              "conversation": {
                "lock_after_merge": false
              }
            }'
  changed_files:
    # NOTE:
    # - This is limited to pull_request* events and would raise an error for other events.
    # - A maximum of 3000 files can be returned.
    # - For more flexibility and no limitations see "Using local .git history" above.

    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            cat $file
            echo "\n"
          done